# Exported from Render on 2025-07-12T09:43:52Z
services:
- type: web
  name: nepaliParser
  runtime: python
  repo: https://github.com/gladiolus-language-nectar-profile/nepaliParser
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app.wsgi
  autoDeployTrigger: commit
version: "1"
